// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_s0WZ0hY8KUgrOkaYFQpTZk3O6YtkHo0',
    appId: '1:1067827362468:web:9c675132c3640408494431',
    messagingSenderId: '1067827362468',
    projectId: 'flutter-webrtc-client',
    authDomain: 'flutter-webrtc-client.firebaseapp.com',
    storageBucket: 'flutter-webrtc-client.appspot.com',
    measurementId: 'G-FJHCKPXW5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6PFoHwuf5tt_HxHsYlngj_ev3sMT5hNM',
    appId: '1:1067827362468:android:f836a9c34a7f2b68494431',
    messagingSenderId: '1067827362468',
    projectId: 'flutter-webrtc-client',
    storageBucket: 'flutter-webrtc-client.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP85JfYJdx_qAPZWuPsfCZbnxMdaGwNXI',
    appId: '1:1067827362468:ios:bee42d482f23ce87494431',
    messagingSenderId: '1067827362468',
    projectId: 'flutter-webrtc-client',
    storageBucket: 'flutter-webrtc-client.appspot.com',
    androidClientId: '1067827362468-snrecq53ufgnv5jap2tdu2rjtlbmtr67.apps.googleusercontent.com',
    iosClientId: '1067827362468-8b1bii3l643r4fbbc86g2dil767t1c8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtcClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP85JfYJdx_qAPZWuPsfCZbnxMdaGwNXI',
    appId: '1:1067827362468:ios:bee42d482f23ce87494431',
    messagingSenderId: '1067827362468',
    projectId: 'flutter-webrtc-client',
    storageBucket: 'flutter-webrtc-client.appspot.com',
    androidClientId: '1067827362468-snrecq53ufgnv5jap2tdu2rjtlbmtr67.apps.googleusercontent.com',
    iosClientId: '1067827362468-8b1bii3l643r4fbbc86g2dil767t1c8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebrtcClient',
  );
}
